apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-server-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-server-app
  template:
    metadata:
      labels:
        app: crud-server-app
    spec:
      containers:
        - image: midoblgsm/safrad:latest
          name: container1
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: server-side-configs
